SWEAR_FILTER_WORDS = {
    'бля', 'блять', 'блядь', 'блядина', 'блядский', 'блядство', 'блядун', 'блядюга',
    'пизда', 'пиздец', 'пиздено', 'пиздёж', 'пиздеть', 'пиздища', 'пиздовать', 'пиздюк', 'пиздюлина', 'пиздюля',
    'ебать', 'ебальник', 'ебало', 'ебанутый', 'ебаный', 'ебарь', 'ебатория', 'ебло', 'ебнуть', 'ёбнуть',
    'ёбаный', 'ёбнутый', 'ёбарь', 'ебливый', 'ебля', 'ёбля',
    'хуй', 'хуёвый', 'хуёвина', 'хуила', 'хуище', 'хуйня', 'хуйло', 'хуета', 'хуетень',
    'хер', 'херня', 'херовый', 'херовина',
    'мудак', 'мудила', 'мудозвон', 'мудоеб', 'мудень',
    'гандон', 'гондон', 'конча', 'мразь', 'мразина',
    'сука', 'сучка', 'сучара', 'сучий', 'сучонок',
    'тварь', 'тварина', 'падла', 'падло', 'уебан', 'уёбок',
    'пидор', 'пидорас', 'пидарас', 'пидрила', 'пидр',
    'долбоёб', 'долбаёб', 'долбоящер', 'выебок', 'выебон',
    'залупа', 'залупка', 'залупень', 'гомик', 'гомосек',
    'дебил', 'дебилоид', 'даун', 'даунит', 'идиот', 'идиотина',
    'кретин', 'кретиноид', 'придурок', 'урод', 'уродина',
    'fuck', 'fucking', 'fucker', 'motherfucker', 'fuckoff',
    'shit', 'shitty', 'bullshit', 'shithead', 'shitface',
    'bitch', 'bitches', 'bitching', 'sonofabitch',
    'ass', 'asshole', 'assface', 'smartass', 'dumbass',
    'dick', 'dickhead', 'dickface', 'dicksucker',
    'pussy', 'pussies', 'cunt', 'cunts', 'whore', 'whores',
    'slut', 'sluts', 'slutty', 'bastard', 'bastards',
    'nigger', 'niggers', 'negro', 'chink', 'spic',
    'бля*', 'пизд*', 'еб*', 'ёб*', 'ху*', 'х*й', 'х*р', 'х*ер', 'м*дак', 'г*вно', 'г*ндон', 'п*дор', 'с*ка',
    'б@я', 'п@зда', 'х@й', 'е@ать', 'ё@ать', 'м@дак', 'г@вно', 'с@ка', 'п@дор',
    'б1я', 'п1зда', 'х1й', 'е1ать', 'м1дак', 'г1вно',
    
    'ссать', 'срать', 'срань', 'дерьмо', 'говно', 'говняный',
    'заеб', 'заёб', 'уеб', 'уёб', 'проеб', 'прёб', 'разъеб', 'разёб', 'выеб', 'выебон',
    'сперма', 'сперматозоид', 'кончить', 'конча', 'секс', 'секас', 'трах', 'трахать',
    'шалава', 'шлюха', 'шлюшки', 'проститутка', 'блядунья',
    
    'идинахуй', 'пошлинахуй', 'идивпизду', 'пошёлвпизду', 'идивжопу', 'отъебись', 'отвали', 'заткнись', 'заткнулся',
    'хули', 'нахуя', 'нахер', 'нихуя', 'нихера', 'понахуй', 'похуй', 'похер',
    
    'ублюдок', 'ублюдочный', 'выродок', 'чмо', 'чмошник', 'чмырь', 'отброс', 'отребье',
    'алкаш', 'алкашка', 'пьянь', 'пьяница', 'наркоман', 'наркота', 'drug', 'drugs',
    'алё', 'але', 'пацан', 'пацаны', 'браток', 'братан', 'чёрт', 'чёртов', 'дьявол',
    'сдохни', 'сдох', 'подохни', 'подох', 'сгинь', 'пропади', 'исчезни',
    
    'нацист', 'фашист', 'расист', 'исламист', 'террорист', 'kill', 'murder', 'dead'

    'blya', 'blja', 'blia',
    'bljat', 'bljat\'', 'blyat', 'blyat\'', 'bljatb', 'blyatb',
    'blyad', 'blyad\'', 'bljad', 'bljad\'', 'blyadb', 'bljadb',
    'blyadina', 'bljadina',
    'blyadskij', 'bljadskij', 'blyadskiy',
    'blyadstvo', 'bljadstvo',
    'blyadun', 'bljadun',
    'blyadyuga', 'bljadjuga',

    'pizda', 'pizdec', 'pizdeno',
    'pizdyozh', 'pizdjozh', 'pizdiozh',
    'pizdet\'', 'pizdet', 'pizdetb',
    'pizdisha', 'pizdischa',
    'pizdovat\'', 'pizdovat', 'pizdovatb',
    'pizdyuk', 'pizdjuk',
    'pizdyulina', 'pizdjulina',
    'pizdyulya', 'pizdjylya',

    # Еб/Ёб и производные
    'ebat\'', 'ebat', 'ebatb', 'yebat', 'yebat\'', 'yebatb',
    'ebal\'nik', 'ebalnik', 'yebalnik',
    'ebalo', 'yebalo',
    'ebanutyj', 'ebanuty', 'yebanutyj', 'yebanuty',
    'ebanyj', 'ebany', 'yebanyj', 'yebany',
    'ebar\'', 'ebar', 'yebar',
    'ebatoriya', 'yebatoriya',
    'eblo', 'yeblo',
    'ebnut\'', 'ebnut', 'yebnut\'', 'yebnut',
    'yobat\'', 'yobat', 'yobatb',
    'yobanyj', 'yobany',
    'yobnutyj', 'yobnuty',
    'yobar\'', 'yobar',
    'eblivyj', 'yeblivyj',
    'eblya', 'yeblya', 'yoblya',

    'huj', 'khuj', 'huy', 'khuy',
    'huyovyj', 'huyoviy', 'khuyevyj',
    'huyovina', 'khuyovina',
    'huila', 'khuyila',
    'huishhe', 'huische', 'khuyishche',
    'hujnya', 'huynya', 'khuynya',
    'hujlo', 'huilo', 'khujlo',
    'hueta', 'khuyeta',
    'hueten\'', 'hueten', 'khuyeten',
    'her', 'kher',
    'hernya', 'khernya',
    'herowyj', 'heroviy', 'kherovyj',
    'herovina', 'kherovina',

    'mudak', 'moodak',
    'mudila', 'moodila',
    'mudozvon', 'moodozvon',
    'mudoeb', 'moodoyeb',
    'muden\'', 'muden',

    'gandon', 'gondon', 'kondon',
    'koncha', 'koncha',
    'mraz\'', 'mraz', 'mrazb',
    'mrazina',

    'suka', 'sooky',
    'suchka', 'soochka',
    'suchara', 'soochara',
    'suchij', 'soochij',
    'suchonok', 'soochonok',

    'tvar\'', 'tvar', 'tvarb',
    'tvarina',
    'padla', 'padlo',
    'ueban', 'uyeban',
    'uyobok', 'uyebok',

    'pidor', 'peder',
    'pidoras', 'pederas',
    'pidaras',
    'pidrila',
    'pidr', 'pidor',

    'dolboyob', 'dolboeb',
    'dolbaeb', 'dolbayob',
    'dolboyashher', 'dolbojascher',
    'vyebok', 'viebok',
    'vyebon', 'viebon',

    'zalupe', 'zalupa',
    'zalupka',
    'zalupen\'', 'zalupen',
    'gomik',
    'gomosek', 'homosek',

    'debil', 'dyebil',
    'debiloid', 'dyebiloid',
    'daun', 'dawn',
    'daunit', 'dawnit',
    'idiot', 'ydiot',
    'idiotina', 'ydiotina',
    'kretin', 'kreten',
    'kretinoid', 'kretenoid',
    'pridurok', 'pridyrok',
    'urod', 'yrod',
    'urodina', 'yrodina',

    'fuck', 'fucking', 'fucker', 'motherfucker', 'fuckoff',
    'shit', 'shitty', 'bullshit', 'shithead', 'shitface',
    'bitch', 'bitches', 'bitching', 'sonofabitch',
    'ass', 'asshole', 'assface', 'smartass', 'dumbass',
    'dick', 'dickhead', 'dickface', 'dicksucker',
    'pussy', 'pussies', 'cunt', 'cunts', 'whore', 'whores',
    'slut', 'sluts', 'slutty', 'bastard', 'bastards',
    'nigger', 'niggers', 'negro', 'chink', 'spic',

    'blya*', 'blja*', 'blia*',
    'pizd*', 'pisd*',
    'eb*', 'yeb*',
    'yob*',
    'hu*', 'xu*', 'kh*',
    'h*j', 'x*j', 'kh*j',
    'h*r', 'x*r', 'kh*r',
    'h*er', 'x*er', 'kh*er',
    'm*dak', 'm*dak',
    'g*vno',
    'g*ndон', 'g*nd0n',
    'p*dor', 'p*dr',
    's*ka',

    'b@ya', 'bl@',
    'p@zda', 'p@zdec',
    'h@y', 'x@y', 'kh@y',
    'e@at\'', 'e@at', 'y@at', 'y@at\'',
    'y@at\'', 'y@at',
    'm@dak',
    'g@vno',
    's@ka',
    'p@dor',

    'bl1a',
    'p1zda',
    'h1y', 'x1y', 'kh1y',
    'e1at\'', 'e1at',
    'm1dak',
    'g1vno',

    'ssat\'', 'ssat',
    'srat\'', 'srat',
    'sran\'', 'sran',
    'der\'mo', 'dermo',
    'govno',
    'govnanyj', 'govnaniy',
    'zaeb', 'zayeb',
    'zayob',
    'ueb', 'uyeb',
    'uyob',
    'proeb', 'proyeb',
    'pryob',
    'raz\'eb', 'raz\'yeb',
    'razeb', 'razeb',
    'razob', 'razyob',
    'vyeb', 'vyeb',
    'vyebon', 'viebon',
    'sperma',
    'spermatozoid',
    'konchit\'', 'konchit',
    'koncha',
    'seks',
    'sekas',
    'trah', 'trakh',
    'trahat\'', 'trahat',
    'shalava', 'schalava',
    'shlyuha', 'schlyuha',
    'shlyushki', 'schlyushki',
    'prostitutka',
    'blyadun\'ya', 'bljadunya',

    # Оскорбительные выражения
    'idinahuj', 'idinakhuy',
    'poshlinahuj', 'poshlinakhuy',
    'idivpizdu', 'idivpizdu',
    'poshyolvpizdu', 'poshelvpizdu',
    'idivzhopy', 'idivjopy',
    'ot\'yebis\'', 'otyebis', 'ot\'yebis', 'otjebis',
    'otvali',
    'zatknis\'', 'zatknis',
    'zatknulsya', 'zatknulsja',
    'huli', 'khuli',
    'nahuya', 'nakhuy',
    'naher', 'nakher',
    'nihuya', 'nikhuy',
    'nihuya', 'nikhuy',
    'nihara', 'nikhera',
    'ponahuj', 'ponakhuy',
    'pohuj', 'pokhuy',
    'pohyer', 'pokher',

    'ublyudok', 'ubludok',
    'ublyudochnyj', 'ubludochniy',
    'vyrodok', 'virodok',
    'chmo',
    'chmoshnik',
    'chmyr\'', 'chmyr',
    'otbros',
    'otreb\'e', 'otrebe',
    'alkash',
    'alkashka',
    'p\'yan\'', 'pyan',
    'p\'yanica', 'pyanitsa',
    'narkoman',
    'narkota',
    'drug', 'drugs',
    'alyo', 'ale',
    'pacan', 'patsan',
    'pacany', 'patsany',
    'bratok',
    'bratan',
    'chyort', 'chort',
    'chyortov', 'chortov',
    'd\'yavol', 'dyavol',
    'sdohni', 'sdokhni',
    'sdoh', 'sdokh',
    'podohni', 'podokhni',
    'podoh', 'podokh',
    'sgin\'', 'sgin',
    'propadi',
    'ischezni',
    'nacist', 'natsist',
    'fashist',
    'rasist',
    'islamist',
    'terrorist',
    'kill',
    'murder',
    'dead'
}

def chech_swearing_number(message:str):
    if not message or not message.strip():
        return 0
    words = message.split()
    total_counter = 0
    for word in words:
        if word in SWEAR_FILTER_WORDS:
            total_counter += 1
    return total_counter