// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Segun228/MAN_Alpha_bot/services/user-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// AddBusinessToUser mocks base method.
func (m *MockUser) AddBusinessToUser(ctx context.Context, userID int, business models.Business) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBusinessToUser", ctx, userID, business)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBusinessToUser indicates an expected call of AddBusinessToUser.
func (mr *MockUserMockRecorder) AddBusinessToUser(ctx, userID, business any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBusinessToUser", reflect.TypeOf((*MockUser)(nil).AddBusinessToUser), ctx, userID, business)
}

// CreateUser mocks base method.
func (m *MockUser) CreateUser(ctx context.Context, user models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUser)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUser) DeleteUser(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUser)(nil).DeleteUser), ctx, userID)
}

// GetTgIDByUserID mocks base method.
func (m *MockUser) GetTgIDByUserID(ctx context.Context, userID int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgIDByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgIDByUserID indicates an expected call of GetTgIDByUserID.
func (mr *MockUserMockRecorder) GetTgIDByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgIDByUserID", reflect.TypeOf((*MockUser)(nil).GetTgIDByUserID), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUser) GetUserByID(ctx context.Context, userID int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUser)(nil).GetUserByID), ctx, userID)
}

// GetUserByLogin mocks base method.
func (m *MockUser) GetUserByLogin(ctx context.Context, login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUserMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUser)(nil).GetUserByLogin), ctx, login)
}

// GetUserByTgID mocks base method.
func (m *MockUser) GetUserByTgID(ctx context.Context, tgID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTgID", ctx, tgID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTgID indicates an expected call of GetUserByTgID.
func (mr *MockUserMockRecorder) GetUserByTgID(ctx, tgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTgID", reflect.TypeOf((*MockUser)(nil).GetUserByTgID), ctx, tgID)
}

// GetUserIDByTgID mocks base method.
func (m *MockUser) GetUserIDByTgID(ctx context.Context, tgID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByTgID", ctx, tgID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByTgID indicates an expected call of GetUserIDByTgID.
func (mr *MockUserMockRecorder) GetUserIDByTgID(ctx, tgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByTgID", reflect.TypeOf((*MockUser)(nil).GetUserIDByTgID), ctx, tgID)
}

// GetUsers mocks base method.
func (m *MockUser) GetUsers(ctx context.Context) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUserMockRecorder) GetUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUser)(nil).GetUsers), ctx)
}

// UpdateUser mocks base method.
func (m *MockUser) UpdateUser(ctx context.Context, user models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUser)(nil).UpdateUser), ctx, user)
}

// MockBusiness is a mock of Business interface.
type MockBusiness struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessMockRecorder
	isgomock struct{}
}

// MockBusinessMockRecorder is the mock recorder for MockBusiness.
type MockBusinessMockRecorder struct {
	mock *MockBusiness
}

// NewMockBusiness creates a new mock instance.
func NewMockBusiness(ctrl *gomock.Controller) *MockBusiness {
	mock := &MockBusiness{ctrl: ctrl}
	mock.recorder = &MockBusinessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusiness) EXPECT() *MockBusinessMockRecorder {
	return m.recorder
}

// DeleteBusiness mocks base method.
func (m *MockBusiness) DeleteBusiness(ctx context.Context, businessID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBusiness", ctx, businessID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBusiness indicates an expected call of DeleteBusiness.
func (mr *MockBusinessMockRecorder) DeleteBusiness(ctx, businessID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBusiness", reflect.TypeOf((*MockBusiness)(nil).DeleteBusiness), ctx, businessID)
}

// GetBusinessByID mocks base method.
func (m *MockBusiness) GetBusinessByID(ctx context.Context, businessID int) (*models.Business, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusinessByID", ctx, businessID)
	ret0, _ := ret[0].(*models.Business)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusinessByID indicates an expected call of GetBusinessByID.
func (mr *MockBusinessMockRecorder) GetBusinessByID(ctx, businessID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusinessByID", reflect.TypeOf((*MockBusiness)(nil).GetBusinessByID), ctx, businessID)
}

// GetBusinessOwner mocks base method.
func (m *MockBusiness) GetBusinessOwner(ctx context.Context, businessID int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusinessOwner", ctx, businessID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusinessOwner indicates an expected call of GetBusinessOwner.
func (mr *MockBusinessMockRecorder) GetBusinessOwner(ctx, businessID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusinessOwner", reflect.TypeOf((*MockBusiness)(nil).GetBusinessOwner), ctx, businessID)
}

// GetBusinesses mocks base method.
func (m *MockBusiness) GetBusinesses(ctx context.Context) ([]models.Business, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusinesses", ctx)
	ret0, _ := ret[0].([]models.Business)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusinesses indicates an expected call of GetBusinesses.
func (mr *MockBusinessMockRecorder) GetBusinesses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusinesses", reflect.TypeOf((*MockBusiness)(nil).GetBusinesses), ctx)
}

// GetBusinessesByUserID mocks base method.
func (m *MockBusiness) GetBusinessesByUserID(ctx context.Context, userID int) ([]models.Business, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusinessesByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Business)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusinessesByUserID indicates an expected call of GetBusinessesByUserID.
func (mr *MockBusinessMockRecorder) GetBusinessesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusinessesByUserID", reflect.TypeOf((*MockBusiness)(nil).GetBusinessesByUserID), ctx, userID)
}

// UpdateBusiness mocks base method.
func (m *MockBusiness) UpdateBusiness(ctx context.Context, business models.Business) (*models.Business, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBusiness", ctx, business)
	ret0, _ := ret[0].(*models.Business)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBusiness indicates an expected call of UpdateBusiness.
func (mr *MockBusinessMockRecorder) UpdateBusiness(ctx, business any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBusiness", reflect.TypeOf((*MockBusiness)(nil).UpdateBusiness), ctx, business)
}

// MockReports is a mock of Reports interface.
type MockReports struct {
	ctrl     *gomock.Controller
	recorder *MockReportsMockRecorder
	isgomock struct{}
}

// MockReportsMockRecorder is the mock recorder for MockReports.
type MockReportsMockRecorder struct {
	mock *MockReports
}

// NewMockReports creates a new mock instance.
func NewMockReports(ctrl *gomock.Controller) *MockReports {
	mock := &MockReports{ctrl: ctrl}
	mock.recorder = &MockReportsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReports) EXPECT() *MockReportsMockRecorder {
	return m.recorder
}

// CreateReport mocks base method.
func (m *MockReports) CreateReport(ctx context.Context, report models.Report) (*models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", ctx, report)
	ret0, _ := ret[0].(*models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockReportsMockRecorder) CreateReport(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockReports)(nil).CreateReport), ctx, report)
}

// DeleteReport mocks base method.
func (m *MockReports) DeleteReport(ctx context.Context, reportID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReport", ctx, reportID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReport indicates an expected call of DeleteReport.
func (mr *MockReportsMockRecorder) DeleteReport(ctx, reportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReport", reflect.TypeOf((*MockReports)(nil).DeleteReport), ctx, reportID)
}

// GetByReportsUserID mocks base method.
func (m *MockReports) GetByReportsUserID(ctx context.Context, userID int) ([]models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReportsUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReportsUserID indicates an expected call of GetByReportsUserID.
func (mr *MockReportsMockRecorder) GetByReportsUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReportsUserID", reflect.TypeOf((*MockReports)(nil).GetByReportsUserID), ctx, userID)
}

// GetReportByID mocks base method.
func (m *MockReports) GetReportByID(ctx context.Context, reportID int) (*models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportByID", ctx, reportID)
	ret0, _ := ret[0].(*models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportByID indicates an expected call of GetReportByID.
func (mr *MockReportsMockRecorder) GetReportByID(ctx, reportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportByID", reflect.TypeOf((*MockReports)(nil).GetReportByID), ctx, reportID)
}

// GetReports mocks base method.
func (m *MockReports) GetReports(ctx context.Context) ([]models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReports", ctx)
	ret0, _ := ret[0].([]models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReports indicates an expected call of GetReports.
func (mr *MockReportsMockRecorder) GetReports(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReports", reflect.TypeOf((*MockReports)(nil).GetReports), ctx)
}

// UpdateReport mocks base method.
func (m *MockReports) UpdateReport(ctx context.Context, report models.Report) (*models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReport", ctx, report)
	ret0, _ := ret[0].(*models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReport indicates an expected call of UpdateReport.
func (mr *MockReportsMockRecorder) UpdateReport(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReport", reflect.TypeOf((*MockReports)(nil).UpdateReport), ctx, report)
}
