{
 "title": "Business metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DAU",
   "type": "timeseries",
   "description": "Daily Active Users",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE(timestamp) as time,\n    COUNT(DISTINCT telegram_id) as dau\nFROM messages \nGROUP BY DATE(timestamp)\nORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "WAU",
   "type": "timeseries",
   "description": "Weekly active users",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE(timestamp) as week_start,\n    COUNT(DISTINCT telegram_id) as WAU\nFROM messages \nWHERE timestamp >= CURRENT_DATE - INTERVAL '7 days'\nGROUP BY DATE(timestamp)\nORDER BY week_start DESC;"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "timeseries",
   "description": "Monthly Active Users",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE(timestamp) as week_start,\n    COUNT(DISTINCT telegram_id) as MAU\nFROM messages \nWHERE timestamp >= CURRENT_DATE - INTERVAL '30 days'\nGROUP BY DATE(timestamp)\nORDER BY week_start DESC;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n    telegram_id,\n    COUNT(*) as ratings_count,\n    ROUND(AVG(overall_grade), 2) as avg_rating,\n    MIN(timestamp) as first_rating,\n    MAX(timestamp) as last_rating\nFROM grades\nGROUP BY telegram_id\nHAVING COUNT(*) > 1\nORDER BY ratings_count DESC;"
    }
   ]
  },
  {
   "title": "Динамика метрик оценки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE(timestamp) as day,\n    ROUND(AVG(service_grade), 2) as avg_service,\n    ROUND(AVG(model_grade), 2) as avg_model,\n    ROUND(AVG(overall_grade), 2) as avg_overall,\n    COUNT(*) as rating_count\nFROM grades \nGROUP BY DATE(timestamp)\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Точечные метрики",
   "type": "gauge",
   "description": "Показывает метрики удовлетворенности пользователей нашим сервисом",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE(timestamp) as day,\n    ROUND(AVG(service_grade), 2) as \"Удовлетворенность сервисом\",\n    ROUND(AVG(model_grade), 2) as \"Удовлетворенность моделью\",\n    ROUND(AVG(overall_grade), 2) as \"Общая Удовлетворенность\"\nFROM grades \nGROUP BY DATE(timestamp)\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Live audience",
   "type": "gauge",
   "description": "Shows our current audience",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT telegram_id) as live_users\nFROM messages \nWHERE timestamp >= NOW() - INTERVAL '31 day';"
    }
   ]
  }
 ]
}